docs/tutorials/variant_calling_galaxy_1/variant_calling_galaxy_1.md
=> Fix numbering typo.

docs/tutorials/rna_seq_dge_basic/rna_seq_basic_tuxedo.md, mkdocs.yml
Re-adding the old workshop document (Tuxedo workflow with Tophat and Cuffdiff) because Igor's running a workshop tomorrow.
=> Re-add old RNA-seq tuxedo protocol tutorial

docs/includes/connecting.md, docs/includes/media/slides.css, docs/tutorials/hpc/hpc.md, docs/tutorials/hpc/intro.md, docs/tutorials/hpc/slides.html, mkdocs.yml
* remove link to andrew robinson's version of the tutorial
* remove dependency on environment
* remove dependency on javascript showable
* specific to melbourne bioinformatics hardware
* updated to match look and feel of other tutorials
* updates to content (unmerged changes made by Andrew)
=> update to hpc tutorial

docs/tutorials/docker/docker.md, docs/tutorials/galaxy_101/galaxy_101.md, docs/tutorials/hpc/hpc.md, docs/tutorials/molecular_dynamics_101/molecular_dynamics_101.md, docs/tutorials/rna_seq_dge_basic/rna_seq_basic_tutorial.md, docs/tutorials/unix/intro.md, docs/tutorials/unix/unix.md, docs/tutorials/variant_calling_galaxy_1/variant_calling_galaxy_1.md
This is to give our tutorials a consistent set of "learning objectives" etc.
We have not yet updated all. This PR covers some tutorials we'll use in the next round: Unix, HPC, Intro to Galaxy/GVL, Intro to variant calling, Intro to RNA-seq, molecular modelling, Docker.
=> Update tutorial intros

docs/tutorials/molecular_dynamics_101/molecular_dynamics_101.md, docs/tutorials/molecular_dynamics_201/molecular_dynamics_201.md
Molecular modelling intro update - missed in PR https://github.com/melbournebioinformatics/MelBioInf_docs/pull/75
=> Update molecular modelling tutorials intro

docs/tutorials/singlecell/index.md, mkdocs.yml
A placeholder while we develop our own materials.
=> single cell links

docs/index.md
minor edit to test auto deployment of website.
=> remove whitespace

docs/tutorials/python_viz/python_viz.md
=> changed jupyter notebook link to local fork

docs/tutorials/Genome_browsers/GenomeBrowsers_Intro_short.md
not yet included in the main menu.
for use in BINF90002 subject workshop
=> add short genome browser workshop

mkdocs.yml, overrides/main.html
Added a new GA4 tracking ID (gtag) for analytics. 
Old UA code was commented out.
=> Updated google analytics tracking

README.md
Add layout and formatting template location in adding-a-new-tutorial section.
=> Add layout template location

docs/tutorials/Genome_browsers/GenomeBrowsers_Intro.md
=> minor edit to trigger travis

docs/tutorials/hybrid_assembly/nanopore_assembly.md
=> fix images

docs/tutorials/qiime2/qiime2.md
Edits after Qiime2 practice run.
=> Edit qiime2 tutorial

docs/tutorials/variant_calling_gatk1/variant_calling_gatk1.md
=> Bug fixes for variant calling command line

docs/tutorials/qiime2/qiime2.md
=> Minor edits, added slide link

docs/tutorials/qiime2/qiime2.md
Added training classifier section, updated links
=> Added training classifier section

docs/tutorials/qiime2/qiime2.md
Update slide links and uploaded slides
=> Update slide links and upload slides

.gitignore, docs/tutorials/rna_seq_dge_advanced/rna_seq_advanced_tutorial.md, docs/tutorials/rna_seq_dge_basic/rna_seq_basic_tuxedo.md, mkdocs.yml
=> Removes `mdx_showable` plugin

docs/tutorials/git/git.md
=> Merge changes from feedback meeting

docs/tutorials/seurat-de/seurat-de.md
- **Add link to slides**
- **Add author contributions**
=> Add author contributions

docs/tutorials/seurat-de/seurat-de.md
@manveerchauhan I had to reapply your changes as a new pull request. Please review to see if I'm missing anything.
I've added you as a co-author to the commit.
Best,
Vini
=> Apply changes from workshop review meeting
